/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TorneosRouteImport } from './routes/torneos'
import { Route as NuevoRouteImport } from './routes/nuevo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TorneoIdRouteImport } from './routes/torneo.$id'

const TorneosRoute = TorneosRouteImport.update({
  id: '/torneos',
  path: '/torneos',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevoRoute = NuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TorneoIdRoute = TorneoIdRouteImport.update({
  id: '/torneo/$id',
  path: '/torneo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nuevo': typeof NuevoRoute
  '/torneos': typeof TorneosRoute
  '/torneo/$id': typeof TorneoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nuevo': typeof NuevoRoute
  '/torneos': typeof TorneosRoute
  '/torneo/$id': typeof TorneoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nuevo': typeof NuevoRoute
  '/torneos': typeof TorneosRoute
  '/torneo/$id': typeof TorneoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nuevo' | '/torneos' | '/torneo/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nuevo' | '/torneos' | '/torneo/$id'
  id: '__root__' | '/' | '/nuevo' | '/torneos' | '/torneo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NuevoRoute: typeof NuevoRoute
  TorneosRoute: typeof TorneosRoute
  TorneoIdRoute: typeof TorneoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/torneos': {
      id: '/torneos'
      path: '/torneos'
      fullPath: '/torneos'
      preLoaderRoute: typeof TorneosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nuevo': {
      id: '/nuevo'
      path: '/nuevo'
      fullPath: '/nuevo'
      preLoaderRoute: typeof NuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torneo/$id': {
      id: '/torneo/$id'
      path: '/torneo/$id'
      fullPath: '/torneo/$id'
      preLoaderRoute: typeof TorneoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NuevoRoute: NuevoRoute,
  TorneosRoute: TorneosRoute,
  TorneoIdRoute: TorneoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
